[project]
name = "ncclient-benchmark"
version = "0.1.0"
description = "NETCONF ncclient benchmark"
requires-python = ">=3.14"
dependencies = [
    "ncclient>=0.7.0",
]

[project.scripts]
benchmark = "benchmark:main"
